# Generated by Django 5.0.14 on 2025-04-05 01:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0003_alter_project_description_alter_task_deadline_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
        migrations.AlterModelTable(
            name='task',
            table='Task',
        ),
    ]
