# Generated by Django 5.0.14 on 2025-04-05 01:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_alter_user_email_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assign',
            table='Assign',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
