# Generated by Django 5.0.14 on 2025-04-08 04:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_alter_assign_table_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign',
            old_name='projectId',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='assign',
            old_name='userId',
            new_name='user',
        ),
    ]
